# docker run -p 8761:8761 juliocbms/naming-server:0.0.1-SNAPSHOT
services:

  zipkin-server:
    image: openzipkin/zipkin:3.5.1
    ports:
      - 9411:9411
    restart: always
    networks:
      - julio-network


  naming-server:
    image: juliocbms/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    restart: always
    depends_on:
      - zipkin-server
    networks:
      - julio-network


  api-gateway:
    image: juliocbms/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    restart: always
    depends_on:
      - zipkin-server
      - naming-server
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - julio-network


  book-db:
    image: mysql:9.4.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: book_service
    ports:
      - 3310:3306
    networks:
      - julio-network

  exchange-db:
    image: mysql:9.4.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: exchange_service
    ports:
      - 3308:3306
    networks:
      - julio-network


  exchange-service:
    image: juliocbms/exchange-service
    restart: always
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
    depends_on:
      - zipkin-server
      - naming-server
      - exchange-db
    environment:
      TZ: America/Sao_Paulo
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://exchange-db:3306/exchange_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 8000:8000
    networks:
      - julio-network


  book-service:
    image: juliocbms/book-service
    restart: always
    build:
      context: ./book-service
      dockerfile: Dockerfile
    depends_on:
      - zipkin-server
      - naming-server
      - book-db
    environment:
      TZ: America/Sao_Paulo
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://book-db:3306/book_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 8100:8100
    networks:
      - julio-network


networks:
  julio-network:
    name: julio-network
    driver: bridge